### ISSUE TITLE
MineMarket kredit utalás felhasználónév alapján

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#12]
Üdv!
Ha valakinek a MineMarketben kreditet akarunk utalni, miért az e-mail címe kell hozzá?
Az e-mail címet sokan nem szeretik kiadni, sokkal jobb lenne, ha a felhasználónév megadásával lehetne kreditet utalni valakinek.

**Comment by kgab0r** [comment]
A szerveren hasznalt jatekosnev alapjan

**Comment by andris155** [comment]
Amit a MineMarketbe megadott játékosnevet az alapján.

**Comment by kgab0r** [comment]
Amit a szerveren is hasznal.

**Comment by andris155** [comment]
Köszönjük!
