### ISSUE TITLE
[Bug] Legutóbbi támogatók 2x

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#13]
A legutóbbi támogatók widgetben, ha 1-t írok Megjelenítendő rendelések számához, akkor 2-t jelenít meg, ha 2-t, akkor négyet. Magyarul mindig szorozza 2-vel a számot.
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11020060/93a0e5ba-8613-11e5-8946-ba70823658f2.PNG)

**Comment by kgab0r** [comment]
1-1 illetve 2-2 kerul megjelenitesre a rendes rendeles es az azonnali kozul

**Comment by andris155** [comment]
Értem, nem lehetne ezt külön állítani? pl 2 azonnali, és 1 sima.

**Comment by andris155** [comment]
Vagy az nem megoldható, hogy egybe az egészet, és továbbra is időrendi sorrendben mint ahogy régen volt, csak szerepelnek benne az Azonnali SMS-sel támogatott játékosok is?

**Comment by kgab0r** [comment]
egyben allithato, tenylegesen a legutobbit szedi ossze

**Comment by andris155** [comment]
ok

**Comment by andris155** [comment]
köszönjük!
