### ISSUE TITLE
[Bug] Nem fogadja el a felhasználónevet az elfelejtett jelszóhoz

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#17]
Üdv!
Ezt írja ki, ha felhasználónevet írok be: Már folyamatban van jelszó visszaállítás!
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11046713/35629eea-872f-11e5-8801-8c004cf31311.PNG)
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11046754/5e5d7c5c-872f-11e5-8d81-23853495b5d5.PNG)

**Comment by kgab0r** [comment]
Nem lehetseges, hogy valoban folyamatban lenne visszaallitas?
