### ISSUE TITLE
[Bug] Nem működő elfelejtett jelszó opció

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#18]
Üdv!
Ha e-mail címet írunk be elküldi a jelszó megváltoztató linket e-mailben.
A linkel küld egy új jelszót e-mailben azonban továbbra is csak a régi jelszóval lehet belépni, tehát az új jelszót elküldi, de nem írja át a rendszerben, ezért lehet gondolom csak a régivel továbbra is belépni.
Viszont aki tényleg elfelejti a jelszót az utána jelenleg nem tud többet belépni.
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11046817/abe90ba8-872f-11e5-8ece-8e898ad448bc.PNG)

**Comment by kgab0r** [comment]
Pontosan mely email cimeknel merul fel a problema?

**Comment by andris155** [comment]
Köszönjük!
