### ISSUE TITLE
[Bug] Azonnali SMS támogatás kredit név legutóbbi támogatók

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#21]
Üdv!
Az azonnali SMS támogatók listájában nem használja a rendszer az egyedi kredit nevet, hanem Forintot ír.
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11069715/d7de2a42-87d7-11e5-8603-0484b1949804.PNG)
![kepkivagas2](https://cloud.githubusercontent.com/assets/8324198/11069694/bb591454-87d7-11e5-8fb8-161a08585064.PNG)

**Comment by kgab0r** [comment]
Mivel az azonnali támogató forintban fizet és nem kreditben.

**Comment by andris155** [comment]
Igaz
