### ISSUE TITLE
[Bug] Nem működő Egyedi CSS rész.

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#23]
Üdv!
Az Egyedi css rész nem működik a MineMarketben, ha valaki egyedi css-t akar a html-be kell belinkelnie egy külső oldalról a css fájlt, így működik, de akkor felesleges az Egyedi css rész a MineMarket Admin oldalra.
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11191191/3d516ed6-8c9a-11e5-8905-25857d052b8c.PNG)

**Comment by kgab0r** [comment]
A boxba CSS kodot kell beirni, ha nem latszik az eredmeny, problad meg  !important hasznalataval.

**Comment by andris155** [comment]
A css fájlt linkeltem be inkább a webre, nekem az a megoldás optimálisabb.
