### ISSUE TITLE
[Bug] Nem elérhető a MineMarket

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#28]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11834130/b6db2e36-a3c9-11e5-959c-53168dfa4aa9.PNG)

16.12 07:49:25 [Server] WARN java.util.concurrent.ExecutionException: java.net.NoRouteToHostException: No route to host
16.12 07:49:25 [Server] WARN at java.util.concurrent.FutureTask.report(Unknown Source)
16.12 07:49:25 [Server] WARN at java.util.concurrent.FutureTask.get(Unknown Source)
16.12 07:49:25 [Server] WARN at hu.infinityhosting.bukkit.managers.PurchaseManager$PurchaseProcessor$1.run(PurchaseManager.java:171)
16.12 07:49:25 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
16.12 07:49:25 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
16.12 07:49:25 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
16.12 07:49:25 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
16.12 07:49:25 [Server] WARN at java.lang.Thread.run(Unknown Source)
16.12 07:49:25 [Server] WARN Caused by: java.net.NoRouteToHostException: No route to host
16.12 07:49:25 [Server] WARN at java.net.PlainSocketImpl.socketConnect(Native Method)
16.12 07:49:25 [Server] WARN at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
16.12 07:49:25 [Server] WARN at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
16.12 07:49:25 [Server] WARN at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
16.12 07:49:25 [Server] WARN at java.net.SocksSocketImpl.connect(Unknown Source)
16.12 07:49:25 [Server] WARN at java.net.Socket.connect(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.NetworkClient.doConnect(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.http.HttpClient.openServer(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.http.HttpClient.openServer(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.http.HttpClient.<init>(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.http.HttpClient.New(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.http.HttpClient.New(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
16.12 07:49:25 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
16.12 07:49:25 [Server] WARN at hu.infinityhosting.common.HttpQuery.call(HttpQuery.java:67)
16.12 07:49:25 [Server] WARN at hu.infinityhosting.common.HttpQuery.call(HttpQuery.java:12)
16.12 07:49:25 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
16.12 07:49:25 [Server] WARN ... 3 more

**Comment by andris155** [comment]
Megoldódott.

**Comment by andris155** [comment]
Ismét nem elérhető.

**Comment by kgab0r** [comment]
dolgozunk rajta
