### ISSUE TITLE
[Infó] Timings

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#33]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11914894/3acc466e-a68e-11e5-8a7f-06259639c4d8.PNG)

**Comment by diecode** [comment]
Nem tudom pontosan mi a mondanivalód a képpel, hiszen semmit nem írtál, de vélhetőleg azt furcsálod, hogy a többihez képest igen magas a futás ideje az adott metódusoknak. Nyugodj meg, ezek a folyamatok csak akkor futnak le, amikor terméket frissítesz a MineMarket adminban, mivel ekkor:
- A plugin ellenőrzi az összes MineMarket táblát és módosítja ha a szükséges
- Frissíti a MineMarket menüt, hogy aktuális információkat tartalmazzon

Ezt megoldja 8 ms alatt, ami bőven 20 ticken belül van, így ha másodpercenként módosítasz terméket, az sem fog gondot okozni.

**Comment by andris155** [comment]
Nincs semmi bajom vele, csak egyszer mondtad, hogy csináljak róla Timingset, és gondoltam hátha segít ez a fejlesztésében.

**Comment by diecode** [comment]
Az akkor volt, azóta már ez a verzió van élesben, így van adatom több helyről is, de azért köszönöm, legközelebb írd oda, mi okból küldted.

Kellemes ünnepeket.

**Comment by andris155** [comment]
Rendben, nektek is.
