### ISSUE TITLE
[Plugin fejlesztés] Színes tárgynév mentése a /minemarket save-itemstack id paranccsal.

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#37]
Jelenleg a színes nevű tárgy nevét nem menti el, sima fehér dőlt szöveg lesz, vagy dőlt kék, ha fejlesztett az eszköz, mert ugye a minemarket oldalról kéri le a nevet.

**Comment by diecode** [comment]
Kész, update formájában elérhető.

**Comment by andris155** [comment]
Wow, köszönjük. Te vagy a legjobb. :)

**Comment by diecode** [comment]
Remélem minden úgy működik ahogy kell, nem sok időm volt tesztelni, de azért próbálgattam. Kénytelen voltam hozzáadni egy "Termék ID" sort az item szöveghez, hogy ha név alapján nem tudom azonosítani a terméket, akkor aszerint kell. 
Apropó: Habár látszik, hogy rég léptetek be a MineStatus-ba, fejlesztés miatt törölnünk kellett az eddigi grafikonok adatait ( ilyen ez a beta ) és csak az újabb verziójú pluginnal működik tovább a dolog, így érdemes azt telepíteni ha a jövőben használni szeretnétek.

**Comment by andris155** [comment]
A plugint kipróbáltuk, tetszett, de aztán kiderült, hogy az 1.9-ben elég sok bug van, így muszáj volt szelektálnunk pluginokat, hogy valamivel jobban fusson a szerver. Jelenleg nem sok játékos van már rajta sajnos, mivel az 1.9 kisebb, nagyobb hibái mellet a hostot is dosolta valami hülye. Szóval a szerver már azóta jól fut, de a játékosok egyre kevesebben vannak. Ha stabilabb lesz 1.9, és a host lehet visszarakjuk majd.

**Comment by andris155** [comment]
A MineMarket frissítést pedig, csak holnap délután, vagy este tudom tesztelni.

**Comment by diecode** [comment]
Rendben, csupán tájékoztatás jelleggel közöltem, hogy informálva legyél. A DDoS-ra folyamatosan keressük a megoldást, remélhetőleg sikerül egy megfelelő és optimális megoldást találnunk hamarosan. A MineMarketet teszteltem, nekem működött, de ha bármi gond lenne vele, várom az issuet.

**Comment by andris155** [comment]
Honnan tudom letölteni az új verziót?
A MineMarket admin oldalas elvileg semmit se változott.
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/14284907/cbe25250-fb49-11e5-8f43-160a3efedd39.PNG)

**Comment by andris155** [comment]
Jó lett. Köszönjük!
