### ISSUE TITLE
[Plugin bug] A fejnél nem írja a catbe a szöveget ha klikkelünk rá.

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#39]
![2016-04-20_21 46 01](https://cloud.githubusercontent.com/assets/8324198/14688191/ac3a4472-0741-11e6-9197-2f1a20b4902f.png)
(minden fejnél)

**Comment by diecode** [comment]
Más fejeknél is előfordul, vagy csak az 1.9-eseknél?

**Comment by andris155** [comment]
Sima játékos fejjel is ez van pl.: andris155 feje.

**Comment by andris155** [comment]
Elvileg a többivel sem jó, de ezt nem teszteltem.

**Comment by andris155** [comment]
Hibát nem találtam a logban.

**Comment by diecode** [comment]
Akkor is előfordul a hiba, ha a fejet átnevezed?

**Comment by diecode** [comment]
Felraktam a 2.94-es verziót, légy szíves teszteld.

**Comment by andris155** [comment]
Tökéletesen működik!
Köszönjük!
