### ISSUE TITLE
Paysafecard fizetés

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#8]
Üdv!
Többen írták nekem, hogy jó lenne ha lehetne Paysafecard-al fizetni a MineMarketben. Ehhez viszont nem nagyon értek, így az lenne a kérdésem, hogy ez meg lesz valósítva a jövőben, mint új fizetési lehetőség a MineMarketen, vagy ne is várjak ilyet?

**Comment by kgab0r** [comment]
Integralhato, azonban a szerzodest nem tudjuk mi biztositani a Paysafecardal.

**Comment by andris155** [comment]
okés
